### ISSUE TITLE
Type 'string' is not assignable to type 'TemplateContentType'.ts(2345)

### ISSUE THREAD

**Issue by marto97** [sankalpkataria/to-pdf#4]
Hi,
I am getting this error in `await htmlToPdf(options);` when I use the example code from the documentation:

```Argument of type '{ pdf: { writeStream: fs.WriteStream; }; template: { type: string; content: string; css: { type: string; content: string; }; }; data: { name: string; }; additionalData: { resourceType: string; data: { HELLO: string; }; }; }' is not assignable to parameter of type 'HtmlToPdfOptions'.
  Type '{ pdf: { writeStream: fs.WriteStream; }; template: { type: string; content: string; css: { type: string; content: string; }; }; data: { name: string; }; additionalData: { resourceType: string; data: { HELLO: string; }; }; }' is not assignable to type 'RenderOptions'.
    The types of 'template.type' are incompatible between these types.
      Type 'string' is not assignable to type 'TemplateContentType'.ts(2345)
```

When I remove the code from line 3 till to 17 in https://github.com/sankalpkataria/to-pdf/blob/main/src/types.ts#L3
The error is gone and the pdf-file is exported without any problems.

Is there a better way to fix the issue?

**Comment by marto97** [comment]
@sankalpkataria

**Comment by sankalpkataria** [comment]
Hi @marto97 , sorry for being so late.

`template.type` requires one of the enum values.
You can fix the issue by specifying the template type option as follows

```
template: {
      type: TemplateContentType.FILE, // if the content provided is a file path or TemplateContentType.CONTENT if the content is the actual content.
      ...otherOptions
    },
```

Since the field is an enum type, assigning a string value will throw errors.

I'll update the document to fix the misleading type information.

And please feel free to let me know if you face any other issue.

**Comment by marto97** [comment]
@sankalpkataria thanks, that fixed the issue :+1:
