### ISSUE TITLE
Update puppeteer from "^13.3.2" to "21.4.1"

### ISSUE THREAD

**Issue by CavalcanteLeo** [sankalpkataria/to-pdf#5]
Why is this using a so outdated version?

**Comment by sankalpkataria** [comment]
Hi @CavalcanteLeo , Sorry, was bit busy with the work here, never realized it was outdated. But its updated now. Thanks for raising the issue.

**Comment by CavalcanteLeo** [comment]
now, after the upgrade, it's not working anymore in prod, only on local,

1 error and 1 warning

@sankalpkataria 

thanks

```
 ERROR  [unhandledRejection] read ECONNRESET                                                12:17:14 pm

  at TCP.onStreamRead (node:internal/stream_base_commons:217:20)


  Puppeteer old Headless deprecation warning:
    In the near future `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
```

**Comment by sankalpkataria** [comment]
@CavalcanteLeo Hi, Could you please provide some more info on the error you are getting. I tested this on one of our production apps and it seems to work. We needed to upgrade the node version though. What is the node version you are using?

And the warning is fixed now with the latest update.

**Comment by sankalpkataria** [comment]
Hi @CavalcanteLeo , as I haven't heard from you, I am closing this issue. But if you have any comment or some more information on the error, please feel free to reopen the issue.
